### ISSUE TITLE
Cannot write Input To console output

### ISSUE THREAD

**Issue by Davisa94** [31i73/atom-dbg-gdb#21]
When I start a debug and my program requests a cin, I cannot give it input.
I want to input one of the options as indicated in the screenshot below but cannot. the pane will not accept input.
![image](https://cloud.githubusercontent.com/assets/22718251/26750164/6cc0a00a-47d9-11e7-9516-ff7230b755d1.png)

**Comment by ProPuke** [comment]
Your `output-panel` and `dbg` packages are out of date. Update your Atom to 1.17 for newer features <3

**Comment by Davisa94** [comment]
Thanks

On Jun 5, 2017 6:37 PM, "Luke" <notifications@github.com> wrote:

Closed #21 <https://github.com/31i73/atom-dbg-gdb/issues/21>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/31i73/atom-dbg-gdb/issues/21#event-1110920382>, or mute
the thread

**Comment by pinventado** [comment]
I have the same issue, but I'm not sure if it's because I'm running Atom on Ubuntu inside of Virtual Box.

**Host Operating system**: macOS High Sierra
**Virtual Box Version**: 5.2.18 r124319
**Operating system**: Ubuntu 18.04.1 LTS
**Atom version**: 1.29.0 x 64
**Atom package versions**:
  dbg 1.6.3
  dbg-gdb 1.7.8
  output-panel 0.3.4
